apiVersion: v1
kind: LimitRange
metadata:
  name: example-limit-range
  namespace: default
spec:
  limits:
  - max:
      cpu: "1000m"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2000m"
      memory: "2Gi"
    min:
      cpu: "200m"
      memory: "256Mi"
    type: Pod
