name: Validate MR to Develop

on:
  push:
    branches:
      - develop
      - tests
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade --force-reinstall pip setuptools
        pip install --upgrade -r src/requirements-dev.txt

    - name: Lint code
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Run unit tests
      env:
        RABBITMQ_URI: ${{ secrets.RABBITMQ_URI }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      run: |
        pytest --cov=src src/tests/ci --cov-report=xml:src/tests/ci/coverage.xml

    - name: Charging coverage
      uses: actions/upload-artifact@v3
      with:
          name: coverage-report
          path: src/tests/ci/coverage.xml
          if-no-files-found: warn
          include-hidden-files: false

    - name: Checking code vulnerabilities
      run: |
        bandit -r .

  build:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade --force-reinstall pip setuptools
        pip install --upgrade -r src/requirements.txt

    - name: Build project
      run: |
        # Comando de build, esto puede variar según tu proyecto
        python setup.py sdist bdist_wheel
        ls dist/  # Verifica los artefactos generados

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/*
        asset_name: my-python-project-${{ github.sha }}.tar.gz
        asset_content_type: application/gzip
